# Задание 1. Итерационный метод нахождения СЗ и СВ.

Грамотно протестировать  
Спектральное разложение  

## Введение

[Источник](http://mathhelpplanet.com/static.php?p=metody-resheniya-zadach-o-sobstvennykh-znacheniyakh-i-vektorakh-matritsy)  
Если не работает, то имеет смысл воспользоваться вебархивом.  


Полезные ссылки:  
http://mlwiki.org/index.php/Power_Iteration - здесь дучше объеяснено

https://slemeshevsky.github.io/num-mmf/eigen/html/._eigen-FlatUI001.html

### Постановка задачи

Пусть ${A}$ — действительная числовая квадратная матрица размера ${(n\times n)}$. Ненулевой вектор ${X= \bigl(x_1,\ldots,x_n\bigr)^T}$ размера ${(n\times1)}$, удовлетворяющий условию


${A\cdot X= \lambda\cdot X,\qquad \mathsf{(2.1)}}$

называется собственным вектором матрицы ${A}$. Число ${\lambda}$ в равенстве (2.1) называется собственным значением. Говорят, что собственный вектор ${X}$ соответствует (принадлежит) собственному значению ${\lambda}$.


Равенство (2.1) равносильно однородной относительно ${X}$ системе:


${(A-\lambda E)\cdot X=0\quad (X\ne 0).\qquad \mathsf{(2.2)}}$

Система (2.2) имеет ненулевое решение для вектора ${X}$ (при известном ${\lambda}$) при условии ${|A-\lambda E|=0}$. Это равенство есть характеристическое уравнение:


${|A-\lambda E|= P_n(\lambda)=0,}$(2.3)

где ${P_n(\lambda)}$ — характеристический многочлен n-й степени. Корни ${\lambda_1, \lambda_2,\ldots,\lambda_n}$ характеристического уравнения (2.3) являются собственными (характеристическими) значениями матрицы ${A}$, а соответствующие каждому собственному значению ${\lambda_i,~ i=1,\ldots,n}$, ненулевые векторы ${X^i}$, удовлетворяющие системе


${AX^i=\lambda_iX^i\quad \text{or}\quad (A-\lambda_i E)X^i=0,~~ i=1,2,\ldots,n,}$(2.4)

являются собственными векторами.


Требуется найти собственные значения и собственные векторы заданной матрицы. Поставленная задача часто именуется второй задачей линейной алгебры.


Проблема собственных значений (частот) возникает при анализе поведения мостов, зданий, летательных аппаратов и других конструкций, характеризующихся малыми смещениями от положения равновесия, а также при анализе устойчивости численных схем. Характеристическое уравнение вместе с его собственными значениями и собственными векторами является основным в теории механических или электрических колебаний на макроскопическом или микроскопическом
уровнях.


Различают полную и частичную проблему собственных значений, когда необходимо найти весь спектр (все собственные значения) и собственные векторы либо часть спектра, например: ${\rho(A)= \max_{i}|\lambda_i(A)|}$ и ${\min_{i}|\lambda_i(A)|}$. Величина ${\rho(A)}$ называется спектральным радиусом.


__Замечания__


1. Если для собственного значения ${\lambda_i}$ — найден собственный вектор ${X^i}$, то вектор ${\mu X^i}$, где ${\mu}$ — произвольное число, также является собственным вектором, соответствующим этому же собственному значению ${\lambda_i}$.


2. Попарно различным собственным значениям соответствуют линейно независимые собственные векторы; k-кратному корню характеристического уравнения соответствует не более ${k}$ линейно независимых собственных векторов.


3. Симметрическая матрица имеет полный спектр ${\lambda_i,~ i=\overline{1,n}}$, действительных собственных значений; k-кратному корню характеристического уравнения симметрической матрицы соответствует ровно ${k}$ линейно независимых собственных векторов.


4. Положительно определенная симметрическая матрица имеет полный спектр действительных положительных собственных значений.

### Метод итераций для нахождения собственных значений и векторов


Для решения частичной проблемы собственных значений и собственных векторов в практических расчетах часто используется метод итераций (степенной метод). На его основе можно определить приближенно собственные значения матрицы ${A}$ и спектральный радиус ${\rho(A)= \max_{i}\bigl|\lambda_i(A)\bigr|}$.


Пусть матрица ${A}$ имеет ${n}$ линейно независимых собственных векторов ${X^i,~ i=1,\ldots,n}$, и собственные значения матрицы ${A}$ таковы, что


${\rho(A)= \bigl|\lambda_1(A)\bigr|> \bigl|\lambda_2(A)\bigr|\geqslant \ldots\geqslant \bigl|\lambda_n(A)\bigr|.}$

### Алгоритм метода итераций

1. Выбрать произвольное начальное (нулевое) приближение собственного вектора ${X^{1(0)}}$ (второй индекс в скобках здесь и ниже указывает номер приближения, а первый индекс без скобок соответствует номеру собственного значения). Положить ${k=0}$.


2. Найти ${X^{1(1)}=AX^{1(0)},~ \lambda_1^{(1)}= \frac{x_i^{1(1)}}{x_i^{1(0)}}}$, где ${i}$ — любой номер ${1\leqslant i\leqslant n}$, и положить ${k=1}$.


3. Вычислить ${X^{1(k+1)}=A\cdot X^{1(k)}}$.


4. Найти ${\lambda_1^{(k+1)}= \frac{x_i^{1(k+1)}}{x_i^{1(k)}}}$, где ${x_i^{1(k+1)}, x_i^{1(k)}}$ — соответствующие координаты векторов ${X^{1(k+1)}}$ и ${X^{1(k)}}$. При этом может быть использована любая координата с номером ${i,~ 1\leqslant i\leqslant n}$.


5. Если ${\Delta= \bigl|\lambda_1^{(k+1)}- \lambda_1^{(k)}\bigr|\leqslant \varepsilon}$, процесс завершить и положить ${\lambda_1\cong \lambda_1^{k+1}}$. Если ${\Delta>\varepsilon}$, положить ${k=k+1}$ и перейти к пункту 3.

__Замечания__


1. Процесс последовательных приближений


${\begin{aligned}&X^{1(1)}= AX^{1(0)},\quad X^{1(2)}= AX^{1(1)}= A^{2}X^{1(0)},\quad \ldots,\\ &X^{1(k)}= AX^{1(k-1)}= AA^{k-1}X^{1(0)}= A^kX^{1(0)},\quad \ldots \end{aligned}}$

сходится, т.е. при ${x\to\infty}$ вектор ${X^{1(k)}}$ стремится к собственному вектору ${X^1}$. Действительно, разложим ${X^{1(0)}}$ по всем собственным векторам: ${\textstyle{X^{1(0)}= \sum\limits_{i=1}^{n} c_iX^i}}$. Так как, согласно (2.4), ${AX^i= \lambda_iX^i}$, то


${\begin{aligned}& AX^{1(0)}= X^{1(1)}= \sum\limits_{i=1}^{n} c_i \lambda_iX^i,\quad AX^{1(1)}= A^2X^{1(0)}= X^{1(2)}= \sum\limits_{i=1}^{n} c_i \lambda_i^2X^i,\quad \ldots\\ &A^kX^{1(0)}= X^{1(k)}= \sum\limits_{i=1}^{n} c_i \lambda_i^kX^i= \lambda_1^k\! \left[c_1X^1+ c_2{\left(\frac{\lambda_2}{\lambda_1}\right)\!}^k X^2+ \ldots+ c_n{\left(\frac{\lambda_n}{\lambda_1}\right)\!}^k X^n\right]\!. \end{aligned}}$

При большом ${k}$ дроби ${{\left(\frac{\lambda_2}{\lambda_1}\right)\!}^k, \ldots, {\left(\frac{\lambda_n}{\lambda_1}\right)\!}^k}$ малы и поэтому ${A^kX^{1(0)}= c_1\lambda_1^kX^1}$, то есть ${X^{1(k)}\to X^1}$ при ${k\to\infty}$. Одновременно ${\lambda_1= \lim\limits_{k\to\infty} \frac{x_{i}^{1(k+1)}}{x_{i}^{1(k)}}}$.


2. Вместо применяемой в пункте 4 алгоритма формулы для ${\lambda_1^{(k+1)}}$ можно взять среднее арифметическое соответствующих отношений для разных координат.


3. Метод может использоваться и в случае, если наибольшее по модулю собственное значение матрицы ${A}$ является кратным, т.е.


${\lambda_1= \lambda_2= \ldots= \lambda_s}$ и ${\bigl|\lambda_1\bigr|> \bigl|\lambda_k\bigr|}$ при ${k>s}$.

4. При неудачном выборе начального приближения ${X^{1(0)}}$ предел отношения ${\frac{x_i^{1(k+1)}}{x_i^{1(k)}}}$ может не существовать. В этом случае следует задать другое начальное приближение.


5. Рассмотренный итерационный процесс для ${\lambda_1}$ сходится линейно, с параметром ${c=\frac{\lambda_2}{\lambda_1}}$ и может быть очень медленным. Для его ускорения используется алгоритм Эйткена.


6. Если ${A=A^T}$ (матрица ${A}$ симметрическая), то сходимость процесса при определении ${\rho(A)}$ может быть ускорена.


7. Используя ${\lambda_1}$, можно определить следующее значение ${\lambda_2}$ по формуле ${\lambda_2= \frac{x_i^{1(k+1)}- \lambda_1 x_i^{1(k)}}{x_i^{1(k)}- \lambda_1 x_i^{1(k-1)}}~ (i=1,2,\ldots,n)}$. Эта формула дает грубые значения для ${\lambda_2}$, так как значение ${\lambda_1}$ является приближенным. Если модули всех собственных значений различны, то на основе последней формулы можно вычислять и остальные ${\lambda_j~(j=3,4,\ldots,n)}$.


8. После проведения нескольких итераций рекомендуется "гасить" растущие компоненты получающегося собственного вектора. Это осуществляется нормировкой вектора, например, по формуле ${\frac{X^{1(k)}}{\|X^{1(k)}\|_1}}$.

## Реализация

In [1]:
import numpy as np

In [9]:
# генератор матрицы
#s=5
#matrix = np.random.randint(0, 5, size=(s, s))
matrix = np.array([[3, 4, 3, 2, 1],
                   [2, 3, 0, 2, 3],
                   [1, 4, 1, 4, 0],
                   [4, 1, 1, 1, 0],
                   [3, 2, 0, 2, 4]])
matrix

array([[3, 4, 3, 2, 1],
       [2, 3, 0, 2, 3],
       [1, 4, 1, 4, 0],
       [4, 1, 1, 1, 0],
       [3, 2, 0, 2, 4]])

In [3]:
# прим 6 http://mathprofi.ru/sobstvennye_znachenija_i_sobstvennye_vektory.html

matrix =  np.array([[5, -1, -1],
                   [0, 4, -1],
                   [0, -1, 4]])

In [10]:
np.linalg.eig(matrix) # [0] - сч, [1] - св

(array([10.37099706+0.j        , -0.78530762+2.27184363j,
        -0.78530762-2.27184363j,  1.14551153+0.j        ,
         2.05410664+0.j        ]),
 array([[-0.55121291+0.j        , -0.12609085+0.47385821j,
         -0.12609085-0.47385821j,  0.08161564+0.j        ,
         -0.20034807+0.j        ],
        [-0.44054679+0.j        , -0.1507622 -0.16051803j,
         -0.1507622 +0.16051803j, -0.64279413+0.j        ,
          0.55352898+0.j        ],
        [-0.38489809+0.j        , -0.39114215-0.40351584j,
         -0.39114215+0.40351584j,  0.40906185+0.j        ,
         -0.39159848+0.j        ],
        [-0.3233697 +0.j        ,  0.5860434 +0.j        ,
          0.5860434 -0.j        ,  0.63727102+0.j        ,
         -0.6066386 +0.j        ],
        [-0.49936795+0.j        ,  0.00514935-0.22753815j,
          0.00514935+0.22753815j, -0.08190634+0.j        ,
          0.36346465+0.j        ]]))

In [11]:
# Power Method to Find Largest Eigen Value and Eigen Vector
# Importing NumPy Library
# https://www.codesansar.com/numerical-methods/power-method-largest-eigen-value-vector-python-program.htm
import numpy as np
import sys

"""
# Reading order of matrix
n = int(input('Enter order of matrix: '))

# Making numpy array of n x n size and initializing 
# to zero for storing matrix
a = np.zeros((n,n))

# Reading matrix
print('Enter Matrix Coefficients:')
for i in range(n):
    for j in range(n):
        a[i][j] = float(input( 'a['+str(i)+']['+ str(j)+']='))
"""

a = matrix

# Making numpy array n x 1 size and initializing to zero
# for storing initial guess vector
n = a.shape[0]

x = np.zeros((n))

# Reading initial guess vector
print('Enter initial guess vector: ')
for i in range(n):
    x[i] = float(input( 'x['+str(i)+']='))

# Reading tolerable error
tolerable_error = float(input('Enter tolerable error: '))

# Reading maximum number of steps
max_iteration = int(input('Enter maximum number of steps: '))

# Power Method Implementation
lambda_old = 1.0
condition =  True
step = 1
while condition:
    # Multiplying a and x
    x = np.matmul(a,x)
    
    # Finding new Eigen value and Eigen vector
    lambda_new = max(abs(x))
    
    x = x/lambda_new
    
    # Displaying Eigen value and Eigen Vector
    print('\nSTEP %d' %(step))
    print('----------')
    print('Eigen Value = %0.4f' %(lambda_new))
    print('Eigen Vector: ')
    for i in range(n):
        print('%0.3f\t' % (x[i]))
    
    # Checking maximum iteration
    step = step + 1
    if step > max_iteration:
        print('Not convergent in given maximum iteration!')
        break
    
    # Calculating error
    error = abs(lambda_new - lambda_old)
    print('errror='+ str(error))
    lambda_old = lambda_new
    condition = error > tolerable_error

Enter initial guess vector: 
x[0]=1
x[1]=2
x[2]=3
x[3]=4
x[4]=5
Enter tolerable error: 0.000001
Enter maximum number of steps: 100

STEP 1
----------
Eigen Value = 35.0000
Eigen Vector: 
0.943	
0.886	
0.800	
0.371	
1.000	
errror=34.0

STEP 2
----------
Eigen Value = 10.5143
Eigen Vector: 
1.000	
0.788	
0.644	
0.554	
0.889	
errror=24.485714285714288

STEP 3
----------
Eigen Value = 10.0815
Eigen Vector: 
1.000	
0.807	
0.696	
0.594	
0.916	
errror=0.43276397515528053

STEP 4
----------
Eigen Value = 10.4202
Eigen Vector: 
1.000	
0.802	
0.701	
0.585	
0.909	
errror=0.3386938942927493

STEP 5
----------
Eigen Value = 10.3891
Eigen Vector: 
1.000	
0.799	
0.698	
0.586	
0.906	
errror=0.03106950962277466

STEP 6
----------
Eigen Value = 10.3676
Eigen Vector: 
1.000	
0.799	
0.698	
0.587	
0.906	
errror=0.021510415668128502

STEP 7
----------
Eigen Value = 10.3709
Eigen Vector: 
1.000	
0.799	
0.698	
0.587	
0.906	
errror=0.003306379934588932

STEP 8
----------
Eigen Value = 10.3713
Eigen Vector: 
1.

# Вывод  
Таким образом мы получили алгоритм позволяющий находить наибольшее СЗ и соответствующий ему СВ.  
Результат был проверен хорошо протестированной функцией в NumPy, а также через решенные задачи на mathprofi.